USE [master]
GO

/****** Object:  Database [newDBSYS]    Script Date: 20/03/2024 12:11:33 am ******/
CREATE DATABASE [newDBSYS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'newDBSYS', FILENAME = N'E:\SQL\MSSQL16.SQLEXPRESS\MSSQL\DATA\newDBSYS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'newDBSYS_log', FILENAME = N'E:\SQL\MSSQL16.SQLEXPRESS\MSSQL\DATA\newDBSYS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [newDBSYS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [newDBSYS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [newDBSYS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [newDBSYS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [newDBSYS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [newDBSYS] SET ARITHABORT OFF 
GO

ALTER DATABASE [newDBSYS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [newDBSYS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [newDBSYS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [newDBSYS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [newDBSYS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [newDBSYS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [newDBSYS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [newDBSYS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [newDBSYS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [newDBSYS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [newDBSYS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [newDBSYS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [newDBSYS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [newDBSYS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [newDBSYS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [newDBSYS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [newDBSYS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [newDBSYS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [newDBSYS] SET  MULTI_USER 
GO

ALTER DATABASE [newDBSYS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [newDBSYS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [newDBSYS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [newDBSYS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [newDBSYS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [newDBSYS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [newDBSYS] SET QUERY_STORE = ON
GO

ALTER DATABASE [newDBSYS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [newDBSYS] SET  READ_WRITE 
GO


